### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by mojtabashahkolahi** [openmeetings/openmeetings-moodle-plugin#6] opened 2016-01-21 05:51 UTC
Hi 
I have worked with this plugin about 1 year. but there is a problem with this plugin. after 1 year working with it the number of recorded files has increased and now it is very difficult to find a proper recorded file for download or view. If I have a way to manage the recorded file it is really good.

**Comment by solomax** [comment] 2016-01-21 06:06
duplicate of #4

**Closed as completed by solomax** 2016-01-21 06:06 UTC
Labels: duplicate
